### PR TITLE
Fix column order

### PR DESCRIPTION
**Pull request by neoatlan**
This pr fixes the column order of composite indexes

### CODE REVIEW

**Comment by bellatoris** [comment]
Can you add reference of this patch and more description why this patch is needed?

**Comment by neoatlan** [comment]
There was a failure during the migration process with mysql 8.0 in local and CI environment.
Currently, the column list is created by row order, and it's coming in different order against the actual column order.

It's already patched in later version of django. ([here](https://github.com/django/django/blob/main/django/db/backends/mysql/introspection.py#L264))

**Comment by bellatoris** [comment]
even if i read original PR https://github.com/django/django/pull/9941, but can not understand why it is a problem. Can you elaborate why this fix is needed and what situation is a problem?

**Comment by neoatlan** [comment]
Below one is the thrown error.
```ValueError: Found wrong number (0) of constraints for notification_notificationcategory(application_id, category_key)```

If you look at ([here](https://github.com/sendbird/django/blob/1.11.35/django/db/backends/base/schema.py#L391)) you can see the above error.
`columns` = `['application_id', 'category_key']`
and returned `constraint_names` was an empty array.

I've investigated why it is empty, and the reason was it was comparing `['application_id', 'category_key']` with `['category_key', 'application_id']`.

The comparing value is creating by ([here](https://github.com/sendbird/django/blob/1.11.35/django/db/backends/mysql/introspection.py#L193)).
And I ran above query and compared with normal one.

Then I figured out, the row order was different.

**Pull request merged**
